# Generated by Django 5.0.2 on 2024-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Fecha_Ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Telefono',
            field=models.IntegerField(null=True),
        ),
    ]
